workflows:
  android-native-apk:
    name: Build Android APK (Native)
    max_build_duration: 30
    environment:
      vars:
        JAVA_VERSION: "17"
      android:
        components:
          - build-tools;34.0.0
          - platforms;android-34

    scripts:
      - name: Set up Java
        script: |
          sdk install java $JAVA_VERSION
          sdk use java $JAVA_VERSION

      - name: Prepare Gradle wrapper
        script: |
          cd ClipSync
          chmod +x ./gradlew

      - name: Build debug APK
        script: |
          cd ClipSync
          ./gradlew assembleDebug --stacktrace

    artifacts:
      - ClipSync/app/build/outputs/apk/debug/app-debug.apk
